### PR TITLE
Regridding masks, robustness of dataset_utils functions and bug fixes

### PR DESCRIPTION
**Pull request by sol1105**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
  - This PR fixes issue #342
  - but addresses also other (unlisted) issues and includes new features as well
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [x] I have added my relevant user information to `AUTHORS.md`

#### Updates to `clisops.utils.dataset_utils`
- Adapted `roocs_utils.xarray_utils.xarray_utils` for `clisops`:
(they were added to `clisops.utils.dataset_utils`)
  - `get_coord_by_type`
    Returns now the coordinate name instead of the coordinate as
    `xarray.DataArray` (and optionally a list of further
    matches with the coordinate type)
- Added function `determine_lon_lat_range` to determine the min. and max. lat and lon values
- Added function `fix_unmasked_missing_values_lon_lat` to identify and mask yet unmasked
  missing values in lat and lon arrays.
- Fixed issue in `cf_convert_between_lon_frames` causing the lon frame to not be adjusted
  in case of NaNs in the longitude array, also added `force` option
- Addressed issues in `generate_bounds_curvilinear`:
  - latitudes are now clipped above 90 or below -90 degrees north
  - longitudes are converted to longitude frame -180, 180
  - longitude bounds are adjusted at the Greenwich meridian or anti meridian to avoid grid cells wrapping once or more times around the globe
  - Bounds are generated significantly faster due to making use of index slicing and `numpy.vectorize`
#### Adapted code for changes to `get_coord_by_type` and other `roocs_utils` functions in
- `clisops.core.average`
- `clisops.core.subset`
- `clisops.ops.base_operation`
- `clisops.utils.output_utils`
- `clisops.utils.file_namers`

#### Updates to `clisops.ops.regrid`
- if input and output grid are alike, the original dataset is passed through
  and a warning issued, rather than an exception raised
- Added option to request a land/sea mask for the output grid

#### Updates to `clisops.core.regrid.Grid`
- Added `Grid()` attributes `xinc`, `yinc`, `res`, `smash_mask`, `degen_mask`,
  `contains_smashed_cells`, `contains_degenerate_cells`
- Added method `_verify_bounds` to
  drop the lat/lon bounds if an integrity check fails
- Added method `_grid_detect_smashed_cells` adapted from `ESMF` to
  detect smashed cells
- `mask` DataArray will be added to `Grid().ds` during initialization,
  masking degenerate cells (collapsed and smashed cells)
- Updated `repr`, added
  - grid approx. resolution
  - information whether grid contains degenerate cells
  - information regarding a potential mask
- Add method `_apply_lsm` to apply land or ocean mask, if present in the file
- Updated `detect_extent` to mask unmasked missing lon/lat values and potentially apply `cf_convert_between_lon_frames`
- Updated `detect_coordinate` to remove attributes from (coordinate) variables that
  would result in false positives when calling `ds.cf[coord_type]`
- Fixed `_grid_detect_collapsed_cells` to not only detect cells
  collapsing to points, but also cells collapsing to lines
- Cleaned up duplicate methods between `clisops.utils.dataset_utils`
  and `clisops.core.regrid.Grid`

#### Tests
- Added reference to multiple test datasets newly added to mini-esgf
- Tests previously skipped (as relying on data on HPC's data pools)
  now using mini-esgf datasets
- Tests previously skipped ("bug no longer exists") were adapted to the code and activated
- Adapted multiple tests from `roocs_utils` for the adapted functions
- Adapted multiple tests after changes to above functions
- Added multiple tests for the newly added functions

### Does this PR introduce a breaking change?: 

The behaviour of the regrid operator changes:
- if source and target grid are evaluated equal, before, an Exception was raised, now, a warning is issued and the original dataset is passed through

Some functions of `roocs_utils.xarray_utils.xarray_utils` have been adapted (and modified) into `clisops.utils.dataset_utils`:
- `get_coord_by_type` now returns the name of the coordinate variable and not the coordinate variable
- `get_coord_by_type` optionally returns an additional list with further matches for the coordinate variable and does not raise an Exception when more than one coordinate variable matches the requested type
-  some functions in `clisops.utils.dataset_utils` and `clisops.core.regrid` behave a little differently in terms of raised Expections / Errors:
    - `clisops.utils.dataset_utils`
      - `get_coord_by_type`: raises `ValueError` instead of an `Exception`, if coord_type is not known
      - `detect_coordinate`: raises `KeyError` instead of `AttributeError` if no coordinate could be detected
      - `detect_gridtype`: raises `ValueError` if grid type is not supported (before `InvalidParameterValue` and `Exceptions` were raised inconsistently)
    - `clisops.core.regrid`
      - `Grid.detect_coordinate`: raises `KeyError` instead of `AttributeError` if no coordinate could be detected
    - `clisops.ops.regrid`
      - `Regrid._calculate`: issues `warning` instead of letting `clisops.core.Weights.__init__` raise an `Exception` when input and output grid are alike

### Other information:

### CODE REVIEW

**Comment by cehbrecht** [comment]
@sol1105 @Zeitsperre could we move all methods of xarray_utils from roocs_utils to clisops?
https://github.com/roocs/roocs-utils/blob/master/roocs_utils/xarray_utils/xarray_utils.py

... and either remove them in roocs-utils or mark them as deprecated.

**Comment by Zeitsperre** [comment]
@cehbrecht I think that would be fine. Maybe just add a new file to the `utils` module here?

What's the timeline on replacing `roocs-utils`? Beyond that migration, what else needs to be done to fully deprecate that library?

**Comment by cehbrecht** [comment]
> What's the timeline on replacing `roocs-utils`? Beyond that migration, what else needs to be done to fully deprecate that library?

@Zeitsperre we also need to move the `parameters` utils to clisops. Moving the `xarray_utils`  to clisops as a first step might be a good thing. We just need to make sure that we use the right `roocs_utils` library as long we need it ... keep the upper version limit:
https://github.com/roocs/clisops/blob/002941a890fd8e0878c9c76ad6457ad0d86dcdc6/pyproject.toml#L69 

`daops` and `rook` can always follow with the changes.

**Comment by Zeitsperre** [comment]
@sol1105 I'll manage the merging of the main branch here. Lots of changs, but it should not be too bad, perhaps it'll even run the tests faster? Will move onto this tomorrow or next week.

**Comment by Zeitsperre** [comment]
@sol1105 

This is getting close to compliant with the new testing data structure.

The `KeyError: -1` issues are coming from the testing helper function that extracts the `lon` values from a Dataset. I don't think this will be too hard to address.

For the `test_roll` failures, these are definitely due to changes to `get_coord_by_type` and how they interact with the changes to `calculate_offset`, another easy fix.

Will see if I can make another pass at this next week. Please let me know if you have questions.

**Comment by sol1105** [comment]
@Zeitsperre Thanks a lot for merging in your changes. I will have a look asap.

**Comment by sol1105** [comment]
@Zeitsperre The failing tests are because of the known problem https://github.com/pydata/xarray/issues/7794
I do not think there is any problem on top of that, at least locally all tests passed with `xarray==2023.2.0` and the few tests fail only for newer versions of xarray.

Should `binder/environment.yml` be a link to the repo's `environment.yml` ?

**Comment by Zeitsperre** [comment]
> @Zeitsperre The failing tests are because of the known problem [pydata/xarray#7794](https://github.com/pydata/xarray/issues/7794) I do not think there is any problem on top of that, at least locally all tests passed with `xarray==2023.2.0` and the few tests fail only for newer versions of xarray.

We should maybe set the `pytest.mark.xfail` for these tests with the `xarray` version as the allowed condition. I can add that later today.

> Should `binder/environment.yml` be a link to the repo's `environment.yml` ?

I think that's a good idea. Fewer files that need to be updated.

**Comment by Zeitsperre** [comment]
Trying to re-run tests without multiple workers. I think something in the test may be locking processes, hence why we're seeing hanging. Odd that it only happened on conda though...

**Comment by Zeitsperre** [comment]
@sol1105 I was able to use `pytest-timeout` to fail out the slowest tests and have marked them as such. Most tests should pass now.

I think the regridding tests are way too heavy to reliably use on CI. If we want to be able to use the test builds to validate that our code is working, the build shouldn't take longer than 7 or 10 minutes at most. Is there a way that we can simplify some of these tests while maintaining code coverage?

**Comment by Zeitsperre** [comment]
> @sol1105 @Zeitsperre could we move all methods of xarray_utils from roocs_utils to clisops? https://github.com/roocs/roocs-utils/blob/master/roocs_utils/xarray_utils/xarray_utils.py
> 
> ... and either remove them in roocs-utils or mark them as deprecated.

I'm thinking we can talk about this tomorrow, but I've started a set of branches (all named `modernize`) here and also in `roocs-utils` and `daops`. I'm thinking we can work within those to move the utilities around as needed.

**Comment by Zeitsperre** [comment]
@cehbrecht 

Thanks again for the chat today!

Tests are now passing! If there are no further changes needed here, I think this is safe to merge. I'll begin working on the major refactoring plan following these changes.

**Comment by sol1105** [comment]
@Zeitsperre Thanks for getting this to work. I will have a look on Friday morning whether there was sth to do before the merge.

**Comment by sol1105** [comment]
@Zeitsperre 
Added the changes to `HISTORY.rst` and made the last changes I planned in this PR. So should be fine to merge now.

**Review by Zeitsperre — APPROVED** [review]
A lot going on here, but everything seems to be working better, with minimal changes to the core utilities. LGTM

**Pull request merged**
