### PR TITLE
Fix incorrect longitude values with roll and give ds_roll lon attributes

### PR DESCRIPTION
**Pull request by ellesmith88**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes issue #127 
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated (with summary of main changes)
- [ ] `bumpversion minor` has been called on this branch
- [ ] I have added my relevant user information to `AUTHORS.md`

* **What kind of change does this PR introduce?:** 
Bug fix - fixes the longitude values when a dataset is rolled and also makes sure that the rolled dataset has attributes for longitude.

I tried two methods (in `test_dataset_roll.py`) and the method that changes values using the offset as the index works in all tests. I didn't manage to get the other method to work for all cases where the offset is negative.

### CODE REVIEW

**Comment by ellesmith88** [comment]
Put as draft for now because I keep getting an error when I try to see what's happening in the CI jobs

**Comment by agstephens** [comment]
Hi @ellesmith88: I am getting the same errors at GitHub CI. E.g.:
```
E   FileNotFoundError: [Errno 2] No such file or directory: b'/badc/cmip6/data/CMIP6/CMIP/IPSL/IPSL-CM6A1/Amon/rlds/gr/v20180803/rlds_Amon_IPSL-CM6A-LR_historical_r1i1p1f1_gr_185001-201412.nc'
```

So, I wonder if some tests are expecting `/badc` to be available to all tests now. I am using a Vagrant VM so there is no `/badc` directory.

**Comment by ellesmith88** [comment]
@agstephens  Ah thank you! I couldn't actually see where it was failing on gitlab CI for some reason, it just said error, so I can sort that now. I think I've just forgotten to mark a test to skip if its using real data.

**Comment by ellesmith88** [comment]
Solved this now

**Review by agstephens — APPROVED** [review]
@ellesmith88: Great work. All those extra tests are excellent. Well done for sorting this!

**Pull request merged**
