### PR TITLE
Add missing `rtree` dependency to ensure correct spatial indexing

### LINKED ISSUE #9: some clisops.subset tests are failing with tox ...
* clisops version:
* Python version:
* Operating System:

### Description

I have marked in PR #8 some subset tests with `pytest.xfail` which are failing in a tox environment but are working with a conda environment.

### PR DESCRIPTION
**Pull request by Zeitsperre**
In the process of adding clisops to xclim, I discovered the source of the failing subset tests.

It appears that depending on the way that `geopandas` is installed, it won't necessarily come bundled with the spatial indexing library `rtree`, which is needed for some specific `geopandas` functions. This library was conditionally installed in xclim's `setup.py` and was probably overlooked when the code was ported here.

Adding this library to the requirements has fixed the final failing tests in `/tests/core/test_subset.py/ `. This should be released on PyPI conda-forge as a bugfix patch.

This PR fixes #9

### CODE REVIEW

**Comment by cehbrecht** [comment]
@Zeitsperre thanks for fixing this :)

You have run `bumpversion` but it is not tagged yet? So we can make the 0.3.1 release on master? Need to update the release date in `history.md`.

Do you want to keep the commits in this PR? Please feel free to merge yourself.

**Comment by Zeitsperre** [comment]
I typically tag releases from master, after everything is merged (hence why the date is not set in the 0.3.1 release). I will add the date for today but I'll leave you to tag from master.

Also, I don't have push access to master. It might be that `clisops` access is under a different team at roocs?

**Comment by Zeitsperre** [comment]
@cehbrecht This is good to be merged! Thanks!

**Comment by cehbrecht** [comment]
@Zeitsperre I have given you write access.

**Pull request merged**
