### PR TITLE
Better handling for masked arrays in subset_bbox

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [ ] `bumpversion minor` has been called on this branch
- [ ] I have added my relevant user information to `AUTHORS.md`

* **What kind of change does this PR introduce?:** 

This PR adds a snippet of code that helps deal with masked grids being fed to `subset_bbox`. Essentially, if a grid's `lon` coordinates have all been masked as `numpy.Nan`, the conditions won't trigger examination of the grid coordinates, to see if they need to be wrapped. This adds a check for this instance.

This also adds a few changes to the Travis CI to reduce the number of builds.

* **Does this PR introduce a breaking change?:** 

It shouldn't. Local testing suggests that no new tests are failing. I should add a test for this case.

* **Other information:**:

### CODE REVIEW

**Review by ellesmith88 — APPROVED** [review]
Looks good. Would be good to have a test as well but it makes sense.

**Comment by Zeitsperre** [comment]
@ellesmith88 You're right. I should add one to this before merging. Thanks!

**Comment by Zeitsperre** [comment]
@ellesmith88 @agstephens Would it be possible to push tagging a release to a few hours from now? There's a possibility we could have this PR finished as well!

**Comment by tlogan2000** [comment]
Added a commit to handle descending order coords in irregular grids.   I'm still not sure this is fixing #92 that @ellesmith88 is referring to

**Comment by ellesmith88** [comment]
@Zeitsperre I've done the patch release, but can do another one if you want this in

**Comment by ellesmith88** [comment]
> Added a commit to handle descending order coords in irregular grids. I'm still not sure this is fixing #92 that @ellesmith88 is referring to

I just tested this - using the `C3S_CMIP5_TSICE` dataset in `tests._common.py` and longitude subsetting is still behaiving in the same way as mentioned in the issue.

**Comment by tlogan2000** [comment]
> C3S_CMIP5_TSICE

@ellesmith88 I don't seem to have access to this file... (I did a simple git clone of clisops repo) ...  Is there some mechanism for me to access all the test data?

**Comment by ellesmith88** [comment]
> @ellesmith88 I don't seem to have access to this file... (I did a simple git clone of clisops repo) ... Is there some mechanism for me to access all the test data?

Our test data is currently in a submodule, did you load it with `git submodule update --init` ?

**Comment by Zeitsperre** [comment]
@tlogan2000 Care to try updating this on your end and seeing if we can continue with it?

**Comment by tlogan2000** [comment]
> @tlogan2000 Care to try updating this on your end and seeing if we can continue with it?

Will likely be tomorrow though

**Comment by Zeitsperre** [comment]
@ellesmith88 

> I just tested this using the `C3S_CMIP5_TSICE` dataset in `tests._common.py` and longitude subsetting is still behaving in the same way as mentioned in the issue.

@tlogan2000 and I were able to refresh our environments and fix a few merge-related issues, and re-run all tests. We've figured out that `C3S_CMIP5_TSICE` is a file on your internal infrastructure, so we don't have access to it. Unless this is added to `mini-esgf-data` or another source, we can't help with debugging this issue.

For our needs, this PR has dealt with the grid-related problems we encountered in December, so we think it's safe enough to merge. For issue #92, we still want to help out, but it'll need to be tackled in a new PR with an example that demonstrates the problems that we can reproduce ourselves.

I'll just update the History now and merge when that's done.

**Comment by ellesmith88** [comment]
@Zeitsperre Sorry you're right, I had thought it was already part of the test data but can see that I was using the file directly. I'll load it in to the test data and update issue #92 with more details. Thanks 👍

**Pull request merged**
