### PR TITLE
Update xesmf minimal version to 0.6.2

### LINKED ISSUE #206: Update xesmf to 0.6.2
* clisops version:
* Python version:
* Operating System:

### Description

0.6.2 fixes a number of bugs with task graph creation and with the computation of the SpatialAverager weights. It would be good to update clisops to this version.

### PR DESCRIPTION
**Pull request by huard**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [x] I have added my relevant user information to `AUTHORS.md`

* **What kind of change does this PR introduce?:** 
- Update xesmf to 0.6.2
- Update expected values for `average_shape` output. 
- Sets `logger_root` log level to INFO instead of DEBUG. numba logging made test outputs unreadable.
- conda-xesmf action workflow will fail if any CI test fails.

* **Does this PR introduce a breaking change?:** 
Should not. Fixes a bug in the SpatialAverager weights. 

* **Other information:** 
Fixes #206.

### CODE REVIEW

**Comment by huard** [comment]
@ellesmith88 Ready for review

**Comment by agstephens** [comment]
Hi @huard, this all looks good to me. 
@ellesmith88 can you please review as well, and check you are happy with config changes. Thanks

**Comment by ellesmith88** [comment]
@huard @agstephens Looks good

**Comment by agstephens** [comment]
Hi @huard please complete the Pull Request checklist and then we can merge this one.

**Comment by huard** [comment]
@agstephens  Done.

**Comment by agstephens** [comment]
👍

**Pull request merged**
