### PR TITLE
Update testing suite

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes issue #xyz
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [x] I have added my relevant user information to `AUTHORS.md`

* **What kind of change does this PR introduce?:** 

- Removes some long-obsolete tests
- Splits the conda CI job to test against xarray-stable and xarray-dev
- Updates condaf CI jobs to use `provision-with-micromamba` with caching
- Sets versions for pytest-loguru, sphinx_rtd_theme, and black that are more current
- `pytest` is now always in colour
- `toxv@v3.0` is now set until `tox-conda` supports `tox@v4.0`

* **Does this PR introduce a breaking change?:** 

Not really, no.

* **Other information:**

### CODE REVIEW

**Comment by cehbrecht** [comment]
@Zeitsperre sounds good to use `micromamba` :) Does the test 3.9 fail due to incompatibilities with the latest xarray? Should the `upstream` test be allowed to fail?

**Comment by Zeitsperre** [comment]
@cehbrecht

That's precisely the reason why the conda-build is failing (I'm going to rename the tests to add the upstream flag for clarity here). I don't think the upstream build should be a blocker to merging a PR (it's something the maintainers need to keep an eye, not the contributors).

As it stands, the only thing blocking merge is an approving review. If we want to make some builds `"required"` in order to merge (like we have on xclim) that's something we could do.  Thoughts?

**Review by cehbrecht — APPROVED** [review]

**Comment by cehbrecht** [comment]
@Zeitsperre I thought we could have an `xfail` for the upstream test ...

**Comment by Zeitsperre** [comment]
@cehbrecht 

Thanks for the approval. Merging now. 

We can set things up that way (technically, it's already setup that way). If we set the build to `continue-on-failure`, We won't see the red X-mark any more (which defeats the purpose in my mind; we don't know if it failed unless we look for ourselves). Neither solution seems ideal.

**Pull request merged**
