### PR TITLE
added workaround for to_netcdf

### PR DESCRIPTION
**Pull request by cehbrecht**
This PR adds a workaround for the hanging `to_netcdf` output.

Related issue in rook:
https://github.com/roocs/rook/issues/55

### CODE REVIEW

**Comment by cehbrecht** [comment]
@ellesmith88 I have fixed tests (black code style). You can merge this branch to your branch (New pull request) or just copy the line with the `with dask.config()` statement and close this one.

**Comment by ellesmith88** [comment]
Thanks @cehbrecht

**Review by ellesmith88 — APPROVED** [review]
@cehbrecht I think this can be merged now

**Comment by cehbrecht** [comment]
@ellesmith88 merged. Thanks :)

**Pull request merged**
