### PR TITLE
using roocs-utils 0.6.2

### PR DESCRIPTION
**Pull request by cehbrecht**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes issue #xyz
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated (with summary of main changes)
- [ ] I have added my relevant user information to `AUTHORS.md`

* **What kind of change does this PR introduce?:** 

Use latest `roocs-utils` 0.6.2 to avoid test failure.

* **Does this PR introduce a breaking change?:** 

* **Other information:**

### CODE REVIEW

**Comment by cehbrecht** [comment]
Update to roocs-utils 0.6.2 with this fix:
https://github.com/roocs/roocs-utils/pull/99

**Review by Zeitsperre — COMMENTED** [review]
Why have an upper pin ?

**Comment by cehbrecht** [comment]
@Zeitsperre 
> Why have an upper pin ?

To avoid the test failure of:
https://github.com/roocs/clisops/blob/master/tests/core/test_average.py#L222

Are you ok with the upper pin?

**Comment by Zeitsperre** [comment]
@cehbrecht Yes, all good! Just curious.

**Pull request merged**
