### PR TITLE
added xclim subset module

### PR DESCRIPTION
**Pull request by cehbrecht**
Changes:
* This PR adds the subset module with tests from [xclim](https://github.com/Ouranosinc/xclim). 
* The tests are using test-data from the submodule: https://github.com/roocs/xclim-testdata.
* Installation doc updated with notes for conda environment and submodule initialization.

### CODE REVIEW

**Comment by cehbrecht** [comment]
@ellesmith88 I have moved `test_subset.py` to `test_operations`.

**Comment by cehbrecht** [comment]
@ellesmith88 I have tested like this:
```
$ git submodule update --init 
$ conda env create -f environment.yml
$ conda activate clisops
$ python setup.py develop
$ pip install -r requirements_dev.txt
$ pytest tests/
```

All tests passed ...

I will try to fix travis with a new PR (see #2)

**Comment by ellesmith88** [comment]
@cehbrecht Thanks, I realised I was doing something wrong with the testing. I'm happy with it.

**Comment by cehbrecht** [comment]
@ellesmith88 merged. Thanks for review :)

**Pull request merged**
