### PR TITLE
Set keep_attrs=True in call to SpatialAverager

### PR DESCRIPTION
**Pull request by huard**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes issue #199
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
  - nothing needs updating for this change
- [x] HISTORY.rst has been updated (with summary of main changes)
- [x] I have added my relevant user information to `AUTHORS.md`

* **What kind of change does this PR introduce?:** 
Feature

* **Does this PR introduce a breaking change?:** 
No

* **Other information:**

### CODE REVIEW

**Comment by huard** [comment]
@sol1105 Hi Martin, could you please review ?

**Review by sol1105 — APPROVED** [review]
Should both functions in average.py get a `keep_attrs` parameter to make it optional whether the attributes are carried over, with the default then being True?

**Comment by sol1105** [comment]
I also do not see a use-case. Some of the global or variable attributes might be outdated after the operation (like cell_measures, cell_methods, grid, grid_label, history), but if required, that can be dealt with at a later time.

**Comment by agstephens** [comment]
Merging this as discussed with @huard on Slack.

**Pull request merged**
