### PR TITLE
Remove udunits dependency

### PR DESCRIPTION
**Pull request by ellesmith88**
Removing `udunits` dependency. This can be implemented and tests re run once `roocs-utils` has been updated.

Not sure if `rtree<=0.9.1` is required, see my question in:
See https://github.com/roocs/roocs-utils/pull/36

### CODE REVIEW

**Comment by aulemahal** [comment]
As discussed in roocs/roocs-utils#36, I can contribute to this with removing non-vectorized `create_mask` and the `rtree`-`libspatialindex` dependency.

**Comment by ellesmith88** [comment]
@aulemahal That would be great - thanks!

**Comment by aulemahal** [comment]
@Zeitsperre  I would like your input on this, as I don't remember exactly why we didn't remove the non-vectorized version of `create_mask` earlier?

**Comment by Zeitsperre** [comment]
@aulemahal The reasoning build on what @tlogan2000 mentioned on Slack. There are cases where the vectorized version performs much better (I think it's when there are many polygons) than the non-vectorized version. If it turns out that removing one of these can allow us to drop `tree`/`libspatialindex`, I think it would be worth it.

**Comment by tlogan2000** [comment]
I think the vectorized version is probably faster in all cases and the fact that the original is still there is most lilkely simply because it was never refactored out.   For info  : Vectorized version was originally implemented to test/explore suggested improvements in a user submitted xclim issue.    We might have originally decided to keep both just in case a bug appeared down the road,  with the idea that  we could eventually switch permanently and we simply forgot to revisit

**Comment by ellesmith88** [comment]
@aulemahal @Zeitsperre I've updated `roocs-utils` to version 0.1.5 so `udunits` is no longer required. Are you happy for this change to go ahead?

**Review by Zeitsperre — APPROVED** [review]
Wow! It's a lot lighter now! This will be much easier to install/maintain. Nicely done!

**Comment by ellesmith88** [comment]
Thanks very much @aulemahal 😄

**Pull request merged**
