### PR TITLE
Replace function utils.dataset_utils.check_lon_alignment to fix #217

### LINKED ISSUE #217: Encountering problem with `clisops.ops.subset` related to `clisops.utils.dataset_utils.check_lon_alignment`
* clisops version: latest

### Description

The problem is related to the Issue #35 / PR #117. The function `check_lon_alignment` in `clisops.utils.dataset_utils` converts the longitude coordinate of a dataset between the two longitude frames `[0, 360]` and `[-180, 180]`, depending on the longitude interval selected for the subset operation. When I tested it (see below), the longitude bounds, unlike the longitude axis itself, were not converted.

### What I Did

In the following example, the longitude values are converted to the `[-180, 180]` frame and a roll is performed (internally by `check_lon_alignment`) before the actual subset  operation is performed. After completion, the `lon_bounds` however are still in the old longitude frame `[0, 360]`:

```python
import xarray as xr
import clisops.ops as clops
import cf_xarray as cfxr

ds = xr.tutorial.open_dataset('air_temperature')

# Create bounds
dsb = ds.cf.add_bounds("lon")
dsb = dsb.cf.add_bounds("lat")
print(repr(dsb))
print("-"*30)

# ops subset - bounds become incorrect
outputs = clops.subset(
        ds=dsb,
        area=(-120, 20, -150, 70),
        output_type="xarray",
    )
print(repr(outputs[0]))
```
* Before: 
```
   lon         200.0 202.5 205.0 207.5 ... 325.0 327.5 330.0
   lon_bounds  198.8 201.2 203.8 ... 326.2 328.8 331.2
```
* After:
```
  lon          -150.0 -147.5 -145.0 ... -125.0 -122.5 -120.0
  lon_bounds   208.8 211.2 213.8 ... 236.2 238.8 241.2
```

In contrast to that, the wrapper function `check_lons` in `clisops.core.subset` adjusts the longitude selection interval to the longitude frame of the dataset (which however has the disadvantage that the case of crossing the 0-meridian is not always defined):
```python
# core subset - bounds correct
from clisops.core import subset
ds_out=subset.subset_bbox(dsb, lat_bnds=[20, 70], lon_bnds=[-150, -120])
print(repr(ds_out))
```
* Results in:
```
  lon          210.0 212.5 215.0 217.5 ... 235.0 237.5 240.0
  lon_bounds   208.8 211.2 213.8 ... 236.2 238.8 241.2
```

### Suggestion

I suggest to adjust `check_lon_alignment` in the following way, which should also allow the conversion between the two longitude frames `[0, 360]` / `[-180, 180]` for curvilinear grids (i.e. 2D coordinate variables):
* if conversion is necessary:
    *  if in frame [-180, 180], add 360 to lon and lon_bnds for values < 0
    *  if in frame [0, 360], subtract 360 from lon and lon_bnds for values > 180
* after conversion, instead of a `roll`, perform a `sortby(lon dimension)` to ensure the data can subsetted:
     * rectilinear case (1D coordinate vars): `ds.sortby(lon)`
     * curvilinear case (2D coordinate vars): 
          * overwrite the longitude index with any of the rows of the 2D longitude coordinate variable, eg.  `ds.assign_coords({"x":ds["lon"][0,:].squeeze().values})` with `x` being the lon dimension
          * now perform the `ds.sortby(x)` 

What are your thoughts regarding this? In the unlikely case I did not overlook anything, the execution of this function could be moved from `ops` to `core`, so `clisops.core.subset.check_lons` is no more necessary (or at least the crossing 0-meridian case is dealt with, which is not implemented there atm).

### PR DESCRIPTION
**Pull request by sol1105**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes issue #217
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [x] I have added my relevant user information to `AUTHORS.md`

* **What kind of change does this PR introduce?:** 

- replace utils.dataset_utils.check_lon_alignment by cf_convert_between_lon_frames:
  + converts either dataset or specified lon interval to another longitude frame if necessary
  + added functionality to adjust shifted longitude frames
- added utils.dataset_utils.detect_bounds and detect_coordinate  (from regrid-main branch)
- added tests for the new functions, added new test datasets
- set minimum cf_xarray version to 0.7 (incl. functionality to read eg. bounds info from encoding dict)
- pin pandas to <1.4 because of failing TestSubsetShape tests

* **Does this PR introduce a breaking change?:** 

It shouldn't.

* **Other information:** 

I had some failed attempts in creating this function. The function `_crosses_0_meridian` was required at some point, but not anymore. It somehow seemed a waste to just remove it. I will remove it when you think there is no use for it expected at some point.

I can add further tests, but I thought it would be better to get some feedback first if I'm on the right track.

### CODE REVIEW

**Comment by sol1105** [comment]
Specifying `ipython_genutils` and `sphinx_rtd_themes` explicitly in the `environment.yml` works for me locally with a fresh environment. I don't know what is going wrong and why it does not install `ipython_genutils` using conda or pip here.

**Comment by ellesmith88** [comment]
Hi @sol1105, thanks so much for all your work on this, I’ve been having a look.

It looks good although it may be useful to split the function `cf_convert_between_lon_frames` up a bit more. For example, the section where you are identifying the grids https://github.com/roocs/clisops/blob/437bcce4e04df1a51c3309de7c931aebc34a78fc/clisops/utils/dataset_utils.py#L140-L145 may be useful as a separate function.

For the `detect_coordinate` and `detect_bounds` functions, these would probably be useful in `roocs_utils` rather than clisops, if they don’t already exist there, as they could be applied elsewhere.

The test `test_convert_lon_frame_shifted()` looks good so it would be great to add some more tests as well on other datasets!

**Comment by ellesmith88** [comment]
Hi @sol1105, the notebook looks good. Yes, we can move all the functions over in one go. I suspect we could merge `detect_coordinate` and `get_coord_by_type` as `get_coord_by_type` returns the coord from which you can access the name?

Yes, I think it would make sense to check the longitude selection interval also

**Comment by sol1105** [comment]
@Zeitsperre I noticed a problem with `clisops.core.subset.check_lons`:

In the following example it is not subsetted correctly, the subsetted dataset still includes all longitude values:

```python
from clisops.ops.subset import subset
import xarray as xr
import numpy as np

ds = xr.Dataset(
    data_vars={"var": (("lat", "lon"), np.ones((5, 10)))},
    coords={
        "lat": ("lat", np.zeros(5)),
        "lon": ("lon", np.arange(-10,0,1)),
    },
)
ds["lat"].attrs = {
    "standard_name": "latitude",
}
ds["lon"].attrs = {
    "standard_name": "longitude",
}

outputs = subset(
        ds=ds,
        area=(-1, 0.0, 10.0, 90.0),
        output_type="xarray",
    )
```

The problem are the following lines in the `check_lons` function, extending the longitude selection interval from `[-1, 10]` to `[-361, 10]`:
https://github.com/roocs/clisops/blob/d7c3d7ad9224618a79622bd26125a7dcd7e5c8d0/clisops/core/subset.py#L262-L266

it probably should be 
```python
 if np.all((ds_lon <= 0) | (np.isnan(ds_lon))) and np.any(kwargs[lon] > 180): 
     if isinstance(kwargs[lon], float): 
         kwargs[lon] -= 360 
     else: 
         kwargs[lon][kwargs[lon] <= 180] -= 360 
```
maybe with a subsequent sort?

I tried to replace `check_lons` with the new function of this PR, but I  encountered some problems with the `subset_gridpoint` function and the tests listed below, so I kept it out of this PR for now.
- TestSubsetShape::test_wraps
- TestSubsetShape::test_subset_multiregions
- TestSubsetGridPoint::test_irregular

The `check_lons` function eventually looked  like this, with ops/subset.py not having any check_lon functionality anymore (in case we want to build upon that at some point):
```python
def check_lons(func):
    @wraps(func)
    def func_checker(*args, **kwargs):
        """
        Reformat user-specified "lon" or "lon_bnds" values based on the lon dimensions of a supplied Dataset or DataArray.

        Examines an xarray object longitude dimensions and depending on extent (either -180 to +180 or 0 to +360),
        will reformat user-specified lon values to be synonymous with xarray object boundaries.
        Returns a numpy array of reformatted `lon` or `lon_bnds` in kwargs with min() and max() values.
        """
        if "lon_bnds" in kwargs:
            lon = "lon_bnds"
        elif "lon" in kwargs:
            lon = "lon"
        else:
            return func(*args, **kwargs)

        args = list(args)
        ds_lon = get_lon(args[0])

        if isinstance(args[0], (xarray.DataArray, xarray.Dataset)):
            if kwargs[lon] is None:
                kwargs[lon] = np.asarray((float(ds_lon.min()), float(ds_lon.max())))
            else:
                kwargs[lon] = np.asarray(kwargs[lon])

            if lon == "lon_bnds":
                args[0], lb, ub = cf_convert_between_lon_frames(
                    args[0], kwargs[lon]
                    )
                kwargs[lon] = np.asarray((lb, ub))
            elif lon == "lon":
                lbi, ubi = (float(kwargs[lon].min()), float(kwargs[lon].max()))
                args[0], lb, ub = cf_convert_between_lon_frames(
                    args[0], (lbi, ubi)
                    )
                if not (np.isclose(lbi, lb, atol=0.1) and np.isclose(ubi, ub, atol=0.1)):
                    if kwargs[lon].shape == ():
                        kwargs[lon] = np.asarray(_convert_interval_between_lon_frames(kwargs[lon], kwargs[lon])[0])
                    else:
                        kwargs[lon] = np.asarray([_convert_interval_between_lon_frames(lonval, lonval)[0] for lonval in list(kwargs[lon])])

        return func(*args, **kwargs)

    return func_checker
```

**Comment by Zeitsperre** [comment]
> The problem are the following lines in the `check_lons` function, extending the longitude selection interval from `[-1, 10]` to `[-361, 10]`:
> 
> https://github.com/roocs/clisops/blob/d7c3d7ad9224618a79622bd26125a7dcd7e5c8d0/clisops/core/subset.py#L262-L266
> 
> it probably should be
> 
> ```python
>  if np.all((ds_lon <= 0) | (np.isnan(ds_lon))) and np.any(kwargs[lon] > 180): 
>      if isinstance(kwargs[lon], float): 
>          kwargs[lon] -= 360 
>      else: 
>          kwargs[lon][kwargs[lon] <= 180] -= 360 
> ```
> 
> maybe with a subsequent sort?

You're right about the intervals. The intention of the `check_lons` was to handle cases where the data ran from 0 to 360 and the user had asked for a subset using -180 to 180 bounds. What we would sometimes see is xarray selecting the inverse of our selection as well, so that also needed to be handled for (with splitting, for polygons/bounding boxes). The goal was not to roll the grid over, since our usage had us manipulating very large netCDFs.

> I tried to replace `check_lons` with the new function of this PR, but I encountered some problems with the `subset_gridpoint` function and the tests listed below, so I kept it out of this PR for now.
> 
>     * TestSubsetShape::test_wraps
> 
>     * TestSubsetShape::test_subset_multiregions
> 
>     * TestSubsetGridPoint::test_irregular

@tlogan2000  and I would be curious to see those changes in a PR as well. I'll be honest in that many of these checks were written as-needed and could probably be replaced or at least optimized, now that our collective familiarity with xarray has improved. Please feel free to tag us both on the PR!

**Comment by sol1105** [comment]
@Zeitsperre @ellesmith88 @agstephens 
I suggest to merge this as a preliminary update, to have that in the next release. It fixes #217 and does not conflict with the `core.subset.check_lons function` afaik. We can then look into editing `check_lons` further in another PR. Would that be ok?

**Comment by Zeitsperre** [comment]
I would be fine with merging as is. It would be good to have a PR that we can try building against downstream, so we can see exactly what needs rearranging in our stack. Thanks for keeping me in the loop @sol1105 !

**Review by cehbrecht — APPROVED** [review]

**Comment by cehbrecht** [comment]
@sol1105 @Zeitsperre merged to get it into the release. We can still patch things after Easter.

**Pull request merged**
