### PR TITLE
improve error message when rolling could not be completed

### PR DESCRIPTION
**Pull request by ellesmith88**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [ ] I have added my relevant user information to `AUTHORS.md`

* **What kind of change does this PR introduce?:** 
Error message improved to include longitude bounds of the dataset when the bounds requested in a subset (`ops.subset`) are not within range and rolling could not be completed.

* **Does this PR introduce a breaking change?:** 

* **Other information:**

### CODE REVIEW

**Review by agstephens — COMMENTED** [review]
@ellesmith88 - this looks good. I think the only change that we could make is to use a different term to _roll_ in the exception that is raised. We understand "roll", but it probably doesn't mean anything to users. So maybe you could rephrase it so that it will make sense to an end-user. Thanks

**Comment by ellesmith88** [comment]
@agstephens I'm struggling to think of how to rephrase it, how does this sound? 

> The input longitude bounds (lon_bnds) are not within the longitude bounds of this dataset and the data could not be converted to this longitude frame successfully. Please re-run your request with longitudes within the bounds of the dataset: (lon_min, lon_max)

I've read it so many times, I'm not even sure this makes sense anymore..

**Comment by agstephens** [comment]
@ellesmith88, here is a slightly tweaked suggestion:

```
The requested longitude subset (lon_bnds) is not within the longitude bounds of this dataset and the data could not be converted to this longitude frame successfully. Please re-run your request with longitudes within the bounds of the dataset: (lon_min, lon_max)
```

I hope that looks alright to you.

**Comment by ellesmith88** [comment]
@agstephens Looks good - I've implemented your suggestion.

**Pull request merged**
