### PR TITLE
Fix broken notebooks aliases and address all docs warnings

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes issue #231 
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated (with summary of main changes)
- [x] I have added my relevant user information to `AUTHORS.md`

* **What kind of change does this PR introduce?:** 

- Fixes a broken symlink that had a newline character, for some odd reason.
- Renamed some sections that were conflicting in notebooks.
- Adjusted some function docstrings that were malformed.
- Fixed sections heading underlines that were too short.
- Fixed code-blocks that were malformed.
- Use autosectionlabel options to prevent errors in HISTORY.rst.

* **Does this PR introduce a breaking change?:** 

Not really. There are some section links that have changed, but this would only affect external links to specific sections of the documentation.

* **Other information:**

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@agstephens 

This is good for review.

This PR fixes most of the documentation that was failing to build. There is a notebook that has programmatic errors. This is probably because of an API change in xarray. The docs will still render this notebook, but it should be fixed.

Once that's been addressed, we should remove `nbsphinx_allow_errors = True` from the `docs/conf.py`.

**Comment by Zeitsperre** [comment]
There seems to be a general problem with Python3.7. Serious hanging when resolving dependencies.

Python3.7 is still supported, but only for security fixes as of March 2022 ([PEP537](https://peps.python.org/pep-0537/). Do we still want to support it?

**Comment by agstephens** [comment]
Thanks @Zeitsperre, this looks great.

**Comment by agstephens** [comment]
> There seems to be a general problem with Python3.7. Serious hanging when resolving dependencies.
> 
> Python3.7 is still supported, but only for security fixes as of March 2022 ([PEP537](https://peps.python.org/pep-0537/). Do we still want to support it?

@cehbrecht: do you have any need to retain support for Python3.7?

**Comment by cehbrecht** [comment]
> @cehbrecht: do you have any need to retain support for Python3.7?

short answer: no. We can got to Python >=3.8

Longer answer: there is still an issue in pywps with multiprocessing job queue. It does not work with Python >=3.8. But we are using slurm ... so we are safe :)

**Comment by agstephens** [comment]
Hi @Zeitsperre, we are happy to retire support for Python3.7.

**Pull request merged**
